default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || '7435' %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: <%= ENV['DB_PORT'] || 5432 %>
  database: <%= ENV['DB_NAME'] || 'postgres' %>

development:
  <<: *default
  database: final-app

test:
  <<: *default
  database: final-app-test

production:
  <<: *default
  database: myapp_production
  # username: levion
